config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
  	resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates_inclusion_of :category, in: ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: { only_integer: true }
  validates :content, :rating, presence: true
  validates_inclusion_of :rating, in: [0, 1, 2, 3, 4, 5]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
   def index
    @reviews = Review.all
  end

	def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else 
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
_<%= simple_form_for(restaurant) do |f| %>
  <div>
    <%= f.input :name %>
  </div>
 
  <div>
    <%= f.input :address %>
  </div>
  <div>  
    <%= f.input :phone_number %>
  </div>
  <div>  
    <%= f.input :category %>
  </div>
  
  <%= f.submit class: "btn btn-primary mt-1"%>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<% @restaurants.each do |restaurant| %>
	<div class='m-1'>
		<p><%= link_to restaurant.name, restaurant_path(restaurant)%></p>
	</div>
<% end %>


<%= link_to 'Add a new restaurant', new_restaurant_path, class: "btn btn-primary mt-1"%>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

<%= link_to 'Back to list', restaurants_path, class: "btn btn-primary mt-1"%>

app/views/restaurants/show.html.erb
<h3> Reviews</h3>
	<ul class="list-group">
	  <% @restaurant.reviews.each do |review| %>
	    <li class="list-group-item"><%= review.content %></li>
	    <li class="list-group-item"><%= review.rating %></li>
	  <% end %>
	</ul>

<br>

<%= link_to 'Add a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary mt-1"%>

<%= link_to 'Back to list', restaurants_path, class: "btn btn-primary mt-1"%>

app/views/reviews/_form.html.erb
_<%= simple_form_for(review) do |f| %>
  <div>
    <%= f.input :content %>
  </div>
 
  <div>
    <%= f.input :rating %>
  </div>
    
  <%= f.submit class: "btn btn-primary mt-1"%>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>
_<%= simple_form_for [ @restaurant, @review] do |f| %>
	<%= f.input :content %>
    <%= f.input :rating %>
	<%= f.submit class: "btn btn-primary mt-1"%>
<% end %>

<%= link_to 'Back to list', restaurant_reviews_path, class: "btn btn-primary mt-1"%>